var dataJson = {
  author: "Erik Gonzalez",
  currentRole: "Senior Software Engineer",
  headline: "Enterprise AI & Distributed Systems",
  tagline: "Based in Estonia · Building reliable software from anywhere",
  email: "erik@erikhu.com",
  avatar: "avatar.jpg",
  summary:
    "I design and deliver secure, production-grade platforms across enterprise AI, distributed systems, and real-time products. I work from architecture to operations, with a focus on clear boundaries, resilient integrations, and software teams can confidently evolve.",
  focusAreas: ["Enterprise AI", "Elixir & Python", "Platform engineering"],
  impactHighlights: [
    {
      value: "AI",
      label: "Enterprise assistant platform led from architecture to production",
    },
    {
      value: "Millions",
      label: "Monthly transactions supported in high-volume systems",
    },
    {
      value: "600+",
      label: "Commits delivered across two products in five months",
    },
  ],
  pullQuote:
    "I believe that the best teams are those where everyone feels safe asking 'dumb questions,' where feedback is honest and kind, and where we push each other to do better—not for ego, but for pride in our craft.",
  last_updated: "2026-08-18",
  bio: [
    "I'm a Senior Software Engineer who lives for elegant code, tricky bugs, and that sweet feeling when something just works. My go-to tech is Elixir (because who doesn't enjoy writing readable, concurrent code?), but I don't shy away from fullstack challenges. I'll happily jump into frontend or backend work as needed.",
    "I'm always learning and love experimenting with side projects. Mentoring junior devs, reviewing pull requests with a fine-tooth comb, and spotting architecture smells are things I secretly enjoy.",
    "Outside of code, I'm probably digging into something new in the open-source world or geeking out over a tool someone just released. Let's build things that last and have fun doing it.",
  ],
  languages: ["Ruby", "PHP", "Elixir", "JavaScript", "TypeScript", "Java"],
  humanLanguages: ["Spanish", "English", "Estonian (A2)"],
  frameworks: [
    "Laravel",
    "Ruby on Rails",
    "Phoenix Framework",
    "Vue.js",
    "React Native",
    "Android",
  ],
  softSkills: [
    "Problem solving",
    "Algorithms",
    "Software development",
    "Good communication",
    "GNU/Linux native",
  ],
  tools: [
    "Emacs (Evil)",
    "Docker",
    "Terminal/Console",
    "Zed",
    "Codex",
    "Claude",
    "Hermes",
  ],
  capabilityGroups: [
    {
      name: "AI platforms & agents",
      items: ["Python", "Agno AgentOS", "Claude", "AWS Bedrock", "MCP"],
    },
    {
      name: "Backend & distributed systems",
      items: ["Elixir", "Phoenix", "PostgreSQL", "GraphQL", "RabbitMQ"],
    },
    {
      name: "Security & integrations",
      items: ["Access control", "JWT", "Keycloak", "S3", "Audit logging"],
    },
    {
      name: "Infrastructure & delivery",
      items: ["Docker", "CI/CD", "Observability", "Automated testing"],
    },
  ],
  aiTools: [
    "Claude Code",
    "Gemini",
    "Codex",
    "Copilot",
    "OpenSpec",
    "SpecKit",
    "GSD",
  ],
  openSourceProjects: [
    {
      name: "Shogun",
      description:
        "An Elixir WebSocket client built on top of Gun. Provides a clean API for real-time communication with TLS certificate validation.",
      url: "https://hex.pm/packages/shogun",
      repo: "https://github.com/erikhu/shogun",
      techStack: ["Elixir", "WebSockets", "Gun", "TLS"],
      stats: "1,300+ downloads on Hex.pm",
      license: "GPLv3",
    },
  ],
  hobbies: ["Hiking", "Reading", "Cat/Dog lover <3", "Anime", "Sports"],
  favoriteBooks: [
    "Object Design",
    "Algorithms by Robert Sedgewick",
    "Clean Code",
  ],
  experiences: [
    {
      date: "2014",
      company: "Neurotec",
      role: "Technical Support",
      description:
        "Provided technical support for company systems at a Colombian firm.",
      activities: [],
      techStack: [],
      compact: true,
    },
    {
      date: "2015",
      company: "Coviper",
      role: "Software Developer",
      description:
        "A company I co-founded with a couple of friends. I built WordPress websites, created plugins, and developed mobile apps in Java.",
      activities: [],
      techStack: [
        "WordPress",
        "PHP",
        "Java",
        "JavaScript",
        "HTML",
        "CSS",
        "Git",
      ],
      compact: true,
    },
    {
      date: "2017",
      company: "Freelance",
      role: "Software Developer",
      description:
        "I developed several web projects using Docker and mobile apps such as:",
      activities: [
        "Apartado Stereo (Ionic app) with a basic Laravel web admin used by the app via API.",
        "CallVision (frontend) built in Ionic with Angular 4.",
        "I-Lead web app to create e-cards, built in Ruby on Rails and containerized with Docker.",
        "Alentreno platform built in Ruby on Rails and containerized with Docker.",
        "RadiosFlow: more than 30 apps to listen to radio stations by country, built in my free time. I created a command-line tool in Ruby to automate deployment and compilation of all the apps.",
      ],
      techStack: [
        "Ruby on Rails",
        "JavaScript",
        "Ionic",
        "Angular",
        "Docker",
        "Laravel",
        "Java",
        "Kotlin",
        "HTML",
        "CSS",
        "Bootstrap",
        "Material Design",
        "Git",
      ],
      compact: true,
    },
    {
      date: "2020 - 2022",
      company: "PicallEx",
      role: "Full-Stack",
      description:
        "Built and maintained in-house web, mobile, CRM, API, and real-time telephony products across the full stack.",
      activities: [
        "I am responsible for maintaining the API used by in-house projects and partner companies. I continuously contribute to the CRM, the company's main project. I built the mobile app that helps drivers with deliveries and an in-house telephony panel using modern technologies for real-time and concurrent processes.",
      ],
      techStack: [
        "PHP",
        "JavaScript",
        "TypeScript",
        "Elixir",
        "Docker",
        "Phoenix Framework",
        "Laravel",
        "WebSockets",
        "React Native",
        "Vue.js",
        "Tailwind CSS",
        "HTML",
        "CSS",
        "Git",
      ],
    },
    {
      date: "2022 - 2024",
      company: "Yolo Group - Hub88",
      role: "Elixir Backend",
      description:
        "Core backend engineer responsible for the stability and evolution of a high-volume game aggregation platform and its supporting systems.",
      activities: [
        "Helped keep a game aggregator processing millions of transactions per month stable.",
        "Extended back-office domain logic and integrations using GraphQL, RabbitMQ, and Keycloak.",
        "Supported Tech Ops during critical incidents and contributed to scalable system designs.",
      ],
      techStack: [
        "Elixir",
        "RabbitMQ",
        "Docker",
        "Phoenix Framework",
        "Keycloak",
        "PostgreSQL",
        "GraphQL",
        "Git",
        "Kibana",
      ],
    },
    {
      date: "2024 - Oct 2025",
      company: "Yolo Group - Partners.io",
      role: "Senior Software Engineer",
      description:
        "Led full-stack delivery and engineering quality across high-volume partner products, balancing hands-on development with team enablement.",
      activities: [
        "Planned and delivered projects across backend and frontend while maintaining a high-volume, multi-brand transaction platform.",
        "Modernized a production legacy project with no dedicated team and restored it to active development.",
        "Onboarded and mentored engineers while reinforcing agreed engineering and code-quality standards.",
      ],
      techStack: [
        "Elixir",
        "Docker",
        "Phoenix Framework",
        "Clickhouse",
        "PostgreSQL",
        "Git",
      ],
    },
    {
      date: "Oct 2025 - Mar 2026",
      company: "Bombay Group",
      role: "Senior Software Engineer",
      description:
        "Developed two security-sensitive Elixir/Phoenix products spanning GraphQL APIs, real-time administration workflows, integrations, and platform upgrades.",
      activities: [
        "Built GraphQL APIs with JWT authentication, hashed API keys, real-time subscriptions, audit logging, and tier-based access control.",
        "Delivered LiveView and Surface workflows for uploads, dynamic filtering, and compliance enforcement.",
        "Led Phoenix and LiveView upgrades, maintained CI/CD and static analysis, and contributed more than 600 commits across two products.",
      ],
      techStack: [
        "Elixir",
        "Phoenix Framework",
        "Phoenix LiveView",
        "Surface",
        "Absinthe (GraphQL)",
        "PostgreSQL",
        "JWT (ES256)",
        "ExAws/S3",
        "CircleCI",
        "Dialyzer",
        "Credo",
        "Docker",
        "Slack API",
        "Git",
      ],
    },
    {
      date: "Apr 2026 - present",
      company: "IOENT",
      role: "Senior Software Engineer",
      description:
        "Led the development of a production-grade enterprise AI assistant platform built with Python, Elixir/Phoenix, Agno AgentOS, Claude, AWS Bedrock, and MCP.",
      activities: [
        "Provided natural-language access to authorized tools and data through chat, web, and CLI interfaces.",
        "Implemented persistent conversations, real-time streaming, secure file processing, and document generation.",
        "Established access controls, resilient integrations, observability, automated testing, and Docker-based CI/CD with clear security and privacy boundaries.",
      ],
      techStack: [
        "Python",
        "Elixir",
        "Phoenix Framework",
        "Agno AgentOS",
        "Claude",
        "AWS Bedrock",
        "MCP",
        "Docker",
        "CI/CD",
      ],
      current: true,
    },
  ],
};
